#CI build: build & unit test

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: install .Net Core SDK (3.0 preview 8)
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview8-013656'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: run unit tests
  inputs:
    command: 'test'
    arguments: Net.Code.ADONet.Tests.Unit
- task: DotNetCoreCLI@2
  displayName: integration test (SQLITE)
  inputs:
    command: 'test'
    arguments: 'Net.Code.ADONet.Tests.Integration  --filter Database=SQLITE'
