# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview8-013656'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    arguments: '-p:Version=$(Version)'
- task: DotNetCoreCLI@2
  displayName: unit tests
  inputs:
    command: 'test'
    arguments: Net.Code.ADONet.Tests.Unit
- task: DotNetCoreCLI@2
  displayName: integration test (SQLITE)
  inputs:
    command: 'test'
    arguments: 'Net.Code.ADONet.Tests.Integration  --filter Database=SQLITE'
- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    arguments: ' -p:PackageVersion=$(Version)'
    packagesToPack: 'Net.Code.ADONet/**/*.csproj'
    includesymbols: true
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'