#CI build: build & unit test

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: run unit tests
  inputs:
    command: 'test'
    arguments: Net.Code.ADONet.Tests.Unit
- task: DotNetCoreCLI@2
  displayName: integration test (SQLITE)
  inputs:
    command: 'test'
    arguments: 'Net.Code.ADONet.Tests.Integration  --filter Database=SQLITE'
