name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: restore
      run: dotnet restore
    - name: build
      run: dotnet build
    - name: test
      run: dotnet test Net.Code.ADONet.Tests.Unit
    - name: test
      run: dotnet test Net.Code.ADONet.Tests.Integration  --filter Database=SQLITE
